version: '3.7'

services:
    postgres:
        container_name: postgres
        image: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            PGDATA: /data/postgres
        volumes:
            -   postgres:/data/postgres
        ports:
            -   "5432:5432"
        networks:
            -   postgres
        restart: unless-stopped
    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-uday@jobx.com}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-password}
            PGADMIN_CONFIG_SERVER_MODE: 'False'
        volumes:
            -   pgadmin:/var/lib/pgadmin
        ports:
            -   "5050:80"
        networks:
            -   postgres
        restart: unless-stopped

    config-server-ms:
        image: uday234/config-server-ms:latest
        container_name: config-server-ms
        ports:
            - 8080:8080
        depends_on:
            - servicereg
        networks:
            - microservice-network
            - postgres
        environment:
            - SPRING_PROFILES_ACTIVE=docker

    servicereg:
        image: uday234/servicereg:latest
        container_name: servicereg
        ports:
            - 8761:8761
        depends_on:
            - rabbitmq
            - zipkin
            - postgres
            - pgadmin
        networks:
            - microservice-network
            - postgres
        environment:
            - SPRING_PROFILES_ACTIVE=docker

    companyms:
        image: uday234/companyms:latest
        container_name: company
        ports:
            - 8081:8081
        depends_on:
            - servicereg
            - config-server-ms
        networks:
            - microservice-network
            - postgres
        environment:
            - SPRING_PROFILES_ACTIVE=docker

    jobms:
        image: uday234/jobms:latest
        container_name: job
        ports:
            - 8082:8082
        depends_on:
            - servicereg
            - config-server-ms
        networks:
            - microservice-network
            - postgres
        environment:
            - SPRING_PROFILES_ACTIVE=docker
            - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://servicereg:8761/eureka

    reviewms:
        image: uday234/reviewms:latest
        container_name: review
        ports:
            - 8083:8083
        depends_on:
            - servicereg
            - config-server-ms
        networks:
            - microservice-network
            - postgres
        environment:
            - SPRING_PROFILES_ACTIVE=docker

    gateway-ms:
        image: uday234/gateway-ms:latest
        ports:
            - 8084:8084
        depends_on:
            - servicereg
        networks:
            - microservice-network
            - postgres
        environment:
            - SPRING_PROFILES_ACTIVE=docker

    zipkin:
        image: openzipkin/zipkin
        container_name: zipkin
        ports:
            - 9411:9411
        networks:
            - microservice-network
            -   postgres
        restart: unless-stopped

    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        ports:
            - 5672:5672
            - 15672:15672
        networks:
            - microservice-network
            - postgres


networks:
    microservice-network:
        driver: bridge
    postgres:
        driver: bridge

volumes:
    postgres:
    pgadmin: